apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: test-aws-secretsmanager
    kind: SecretStore
  target:
    name: test-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: hola