apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
  {{- include "aws-xp-eso.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $name }}-aws-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  data:
  {{- toYaml .data | nindent 4 }}