apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  secretStoreRef:
    name: test-aws-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  data:
    hola