apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretsmanager/v1beta1/secret
    uptest.upbound.io/update-parameter: '{"tags":{"updated-by":"crossplane"}}'
  labels:
    example-label: example-secret
  name: example-secret
spec:
  forProvider:
    name: example-withreplica
    recoveryWindowInDays: 0
    region: us-east-1
    replica:
      - region: us-west-1
  providerConfigRef:
    name: aws

# ---

# apiVersion: secretsmanager.aws.upbound.io/v1beta1
# kind: SecretVersion
# metadata:
#   # labels:
#   #   testing.upbound.io/example-name: secretsmanager
#   name: example-secretversion
# spec:
#   forProvider:
#     region: us-east-1
#     secretIdSelector:
#       matchLabels:
#         example-label: example-secret
#     secretStringSecretRef:
#       key: mystery
#       name: example-secret-version
#       namespace: crossplane-system

# ---

# apiVersion: secretsmanager.aws.upbound.io/v1beta2
# kind: SecretRotation
# metadata:
#   annotations:
#     meta.upbound.io/example-id: secretsmanager/v1beta2/secretrotation
#   labels:
#     testing.upbound.io/example-name: secretrotation
#   name: example-secretrotation
# spec:
#   forProvider:
#     region: us-east-1
#     rotationLambdaArnSelector:
#       matchLabels:
#         testing.upbound.io/example-name: secretrotation
#     rotationRules:
#       automaticallyAfterDays: 30
#     secretIdSelector:
#       matchLabels:
#         example-label: example-secret