environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgDKS/N91kVrG4tqniDafv2ZMpFOs8zcK1UgQaLpQwa4AfM2PQFUm7u8sMA0EzG+w4gM/oTCU0/Itz4X4c32RjICYx9VuBEpDpV3TX2jHNmz5jVT1p/zzp8cAsk6aTop9DGp0mRlUfDIdnWs5gLBJPsQuJOrcpZmUaR0Gh1iMbMGdUBHn5v3oJXUddMGlRbUqXGmY8G9y8D3Es3yuznnV25HaSHBLfQjWFXHsiz7jkZGebFwc153uDsGeu0i6lta+e4Hv9hMAAucnYrRBkXaSmDOiZIKZ8vQRP2qFmgSuhgnLsfUx7NphK233ZhR0bmU222R5nI4LvCG3+UjI0eriVh83eULQp/6isGbCzmOd7EqaeL5vRFJXf9zYklc3Ia7j+ds5BiJO01+/wYqVf5UFtHD0Opoa9HbF+uoLAqkFKOOxKt4jv0zGPNusBbfac4CTBUqhXYtul9ceoK1/8Q6Ca8HGePxBoLa9TPEphv5EIuryzONSo6F1gh2TpBYun9xvMJxzK7fYsOlHz7nP47klsE1C9z1NVEX+QmEmyQL76S799Ly+0CDYgE0Xfm+UZ6GCmyy53iR4sesdY2pxZ5yr1ASo3qOjurshGhRUYZ/OJs3VrwhPjJbhCBI0coc494rQfBF6XLCxKzPqilqfVLAQABivFrABhLQTZ2HLrr9YPdy18LJ1mN/NttTyOZlp8+DHG8uF3GakR58ZycnDs8gk7WAwxCHF4LK5hGtq0w= # This value was modified by the sealed-secrets pipeline