environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgAh2UxXGBYjp8xoynKfgmGs8CNq5bUYgzD/DStjxpDUZyc5ANysvZMh0lzdsDf/a7zV0NsGY2JDrC0VI5OgJAz3Zo1Bj12ZKbccBfe0R7C9T6ixCYNH9hMFzv6jZA8jXMHs5HI9sEmx/72xY97k7/fH6yikoSFo2iQP2a/sgpGVip6Y9kqA1AkYg4LbMrReiBvfOboDLSmf1JnlHkEFDLPpS5csiT2AQk8F9XgTBNEuh+GnL0K4vmgxlISd1UY3pRlIZlL+cr+C96ggj0yY0wAQ3QXj5Ry6gA4imBd3QhMzNkFkN5DrkaZoI5MqdIXzJGIdEjhN6KEMrY/xlwpGCsrOXW9avnv4qfXr4ofryQIkLmlL62PZTZqxVsLSK1gYi9yGzipQuE3dncRHBWFG6vjyBJItQYOyh3te540/PFEzQB3VXPv5ezOiL9XMvuzPueWtNzizLUWR+gYZvFmVvp31uyzguEP5izM3bXl3vZn1qmBDHDr7DhEqEkU8xMcPgvRFZqaRNE8tfZDhGCFlyckAVTmmjgWXNOemxVCgnVZJ6zKdk/gNmWoszRP9L15uyLCGbCCZ1TuYgv9ozbBKBsahdBjSUMke8iDjmepj1eh/pnbsdxzkyHhJoByjRU6U+Yy5fNW9z5eveuDRgy1MGy1mZyuJcaZTHjv/6pEPEuCUNX8cPmEHbZgG6QUdFmYUrpU= # This value was modified by the sealed-secrets pipeline