environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgBHoqv+i/NwgI5GpY37eVNlzDhiLn2GHV27qdYbIbYMdc5JAgIs04W9t1q1jXZS0XO9il5+09zD+ETSqv6paihxcCvAeNej5WPS3+r242DL159LiEtDtQSB7KVEwuTJI3bMFrssj6j/fgJftd5uYDJX7W530UA6LqKRoOdnMz2irK4UZMzfBRb0Xx8jz0azWxyOGXxYvCYRR0nDBY6MhGeYAjT0VfLrSyspuLWaHeqNNaPAuNUE9rsMLnifGWWPisZi+bgyHBsc8C48fTD83W8/TqCKJv7ei/tchj/0DUO2S5xxR0sep6vwRaZ+wO0rCtf37Oq79PEcALHZ8BOl7Euxcj3L9/X1UveVWlcu8Vp7hSuzcID/ginDIHHIBJm312WWvQ68YKOYSd3GGniCYytNttQ82dJZKNOVF4FIBBgGGqKi9SSJphX6Ve/Z2WbdIIy6zYLq8+dm5E5hPfCG7k3gSCaKEYfzWcKwvraMHUmU3/0Qf4qyiHaHWQd+ON8TYiQQFlxlrPP3rWS9sAN0e4mzv7BEt/YhR5x5QJNhjVn8FD0ktWFWaRp/aSrj3CZqGCg6id7BFk2t2UOS65SJyqUqBC4eIakqSu23+yBEqiQLGWnV1GJ67MzaSoxDc2d/i7cwfOuU2XwxB8dG1MVhe0CG/WQbs3iiP118EnjeiUpPTUBbMmR9r6mY1v9yHCNM6IrApjDVUXaMTesOL+D1At4O/L7Yt1bbMQN0j7w= # This value was modified by the sealed-secrets pipeline