environment: dev
    
# redis_host: master.meme-web-backend-dev-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redisPass: AgCptNw9U23aiItJs0qcxcRoPvfNHKcqh4eXPkJB3orqoHA7wYtFojc7WDUZUHADKO/uhXhI1tCFoeRkNmLbIr/k2IGQHvTUF8yb+hv86dpHN6r8yrbVbyI0i3JYd3on6UPu/J8OGEHSROaPaaee6lu2spS0UeUtMGlvSrzzk9nZUsZdOKZDcxPnJzV5wpTjrra5d9IXHoFJHvrrPvX9PwozKXILU3/7B2/l2vlGnaNDiPu/xUbf/lXEcMLcgPQ+KfEDYmBxtfzLezGNL3e8x+3lFoiBT3c1hrP5vtcNzsScTKJ0BF7NoK5xIkp5cATxF1d0xc26x3+stFEzBRE/d6ynsca9oNLA1/L4BE4KOGUn0ZP1TOXEIc+mGB5V8D6m2N25XfMb9DNbbNnaKiVTphUvAQTnjLPVQoUQrXT4S9Zp3tkssgVVQGJOB/bLmKKz1eE+vb+rREhKWt9tP/NXKTGzRXkSJUbW8V84N4zIcuK9bwujJqcFPkhbkpPPDCHb4GWjXQhd3iBNqZkObHHdfobOr+tKUkUJnnsK0kT+TuP7lravraks9kYxChoRDoKQ4KVeFkJhFUWocOCsGLHDPpwacXgwvWidjfXv1hOkk5/XCTJDy/4fdCP+aoCpxdrHeD/7qKLwjeJSqNVlOIZJ+p16XVDSB3ujFSEy98ytU96ikA52tAdaGwTvwZGPQr1zv4m2HOObjMMLCq5zDvsuJI1CtOHdTLkYl/PYxKg= # This value was modified by the sealed-secrets pipeline