environment: stage

# redis_host: master.meme-web-backend-stage-ec-rep-grp.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 13
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redisPass: AgAjSyh9HWOYM6Gwv8cF1r9rX6V3jArAtX+8dVfaCsWs90u8+6vmj5AIEr4O91oeyGd5evDQCVsHaPPffs4S0OPWDp/7C1PkH8OFsiPZwzrPVUZ3BYsacrm+xBd/BvCEPm/w3roedOj0r0TQTNpwykrONVEjKDqWm4hFhtKM/oYzqN6yoilXi4hWLXWCoVq8ZfFeC7kIoQxac3byv6soFaLT+PJgV+gxcW3lq0xobyHd0D+muwe55CMDmFPjvPJNt06dtEzEsN/977oBk7cG9p5n6DpSW9UbVixMisAK44OVEHM8n6JLLHeBZBdqu+s624QyYDtL2eUm81ycSf9AeGkIP986hdTcTNfjIJU+9++hUGS2DNDbVwofMGMN8o5S5efYz40+eweH6mRzLE6FzjGtiLPbvnhnCyc6e1WkrI3C8v9XsXwZmYyrnq235kLya2dK7P5NLZmHqYIqo5ISqdsJhXGNzxSLEX048sETcShlvSoljNPUepxBuRg+tOrS46kkhSLn/3TvF+m9ntDgbCHBs0XHtcgRvRq3KX1IRZT06y5S6zE7EJM+Nopi6c6VNBph00Wdq15SGuWJuzhgNdHDU2bS2Z4QjzA1fscHYhk0guSULPg+zwSrVkjNVpfdIFOkT9xly5pj205/xOnSsVM31eV+0IioubVxzRpAUSvebJpcq1fi2FN1meLfg1h5XFxXuxG5xY45f6NaBAiWbnHbL9R8DhNM4BVfEI/v6A== # This value was modified by the sealed-secrets pipeline
