apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-k8s-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
data:
  REDIS_PASS: eyJSRURJU19QQVNTIjoiYXV0b21hdGUtYWxsLXRoZS10aGluZ3MtZGV2In0K # {"REDIS_PASS":"automate-all-things-dev}
type: Opaque

---

apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-crossplane-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  forProvider:
    name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-secret
    recoveryWindowInDays: 0
    region: {{ .Values.region }}
    replica:
      - region: us-west-1
  providerConfigRef:
    name: aws

---

apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-secretversion
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  forProvider:
    region: {{ .Values.region }}
    secretIdRef:
      name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-crossplane-secret
    secretStringSecretRef:
      name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-k8s-secret
      namespace: {{ .Values.system }}-{{ .Values.environment }}
      key: PASSWORD
  providerConfigRef:
    name: aws